name: Publish package to GitHub Packages registry
on:
  push:
    branches:
      - dev-gpr
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@codemonger-io'
      - run: npm ci
      - run: npm -w @codemonger-io/buefy-next run build
      - run: npm -w @codemonger-io/buefy-next publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
