# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit Test Workflow
on:
  push:
    branches:
      - dev
      - main
      # TODO: remove this later
      - trigger-tests
  pull_request:
    branches:
      - dev
      - main
      # TODO: remove this later
      - trigger-tests
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # Node.js v14 bundles npm v6 which does not support workspaces,
    # so we need npm v7 or higher that works with Node.js v14.
    # we are sure that npm v7 works (npm v10 did not btw.)
    - run: npm install -g npm@7
      if: ${{ matrix.node-version == '14.x' }}
    - run: npm ci
    - run: npm -w @ntohq/buefy-next test
